# Generated by Django 4.1.3 on 2022-11-28 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitystudent',
            name='student_name',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='activitystudent',
            name='username',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
