// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v4.25.2
// source: proto/websocket.proto

package websocket

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Type int32

const (
	Type_offer     Type = 0
	Type_answer    Type = 1
	Type_candidate Type = 2
	Type_keepalive Type = 3
	Type_assist    Type = 4
	Type_bye       Type = 5
)

// Enum value maps for Type.
var (
	Type_name = map[int32]string{
		0: "offer",
		1: "answer",
		2: "candidate",
		3: "keepalive",
		4: "assist",
		5: "bye",
	}
	Type_value = map[string]int32{
		"offer":     0,
		"answer":    1,
		"candidate": 2,
		"keepalive": 3,
		"assist":    4,
		"bye":       5,
	}
)

func (x Type) Enum() *Type {
	p := new(Type)
	*p = x
	return p
}

func (x Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Type) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_websocket_proto_enumTypes[0].Descriptor()
}

func (Type) Type() protoreflect.EnumType {
	return &file_proto_websocket_proto_enumTypes[0]
}

func (x Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Type.Descriptor instead.
func (Type) EnumDescriptor() ([]byte, []int) {
	return file_proto_websocket_proto_rawDescGZIP(), []int{0}
}

type Body struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type      Type   `protobuf:"varint,1,opt,name=type,proto3,enum=websocket.Type" json:"type,omitempty"`
	From      string `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	To        string `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
	SessionId string `protobuf:"bytes,4,opt,name=sessionId,proto3" json:"sessionId,omitempty"`
	Data      []byte `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *Body) Reset() {
	*x = Body{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_websocket_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Body) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Body) ProtoMessage() {}

func (x *Body) ProtoReflect() protoreflect.Message {
	mi := &file_proto_websocket_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Body.ProtoReflect.Descriptor instead.
func (*Body) Descriptor() ([]byte, []int) {
	return file_proto_websocket_proto_rawDescGZIP(), []int{0}
}

func (x *Body) GetType() Type {
	if x != nil {
		return x.Type
	}
	return Type_offer
}

func (x *Body) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *Body) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *Body) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *Body) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type AnswerData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sdp        string `protobuf:"bytes,1,opt,name=sdp,proto3" json:"sdp,omitempty"`
	DeviceInfo string `protobuf:"bytes,2,opt,name=deviceInfo,proto3" json:"deviceInfo,omitempty"`
}

func (x *AnswerData) Reset() {
	*x = AnswerData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_websocket_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AnswerData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnswerData) ProtoMessage() {}

func (x *AnswerData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_websocket_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnswerData.ProtoReflect.Descriptor instead.
func (*AnswerData) Descriptor() ([]byte, []int) {
	return file_proto_websocket_proto_rawDescGZIP(), []int{1}
}

func (x *AnswerData) GetSdp() string {
	if x != nil {
		return x.Sdp
	}
	return ""
}

func (x *AnswerData) GetDeviceInfo() string {
	if x != nil {
		return x.DeviceInfo
	}
	return ""
}

type OfferData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sdp        string `protobuf:"bytes,1,opt,name=sdp,proto3" json:"sdp,omitempty"`
	DeviceInfo string `protobuf:"bytes,2,opt,name=deviceInfo,proto3" json:"deviceInfo,omitempty"`
	Media      string `protobuf:"bytes,3,opt,name=media,proto3" json:"media,omitempty"`
}

func (x *OfferData) Reset() {
	*x = OfferData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_websocket_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OfferData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OfferData) ProtoMessage() {}

func (x *OfferData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_websocket_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OfferData.ProtoReflect.Descriptor instead.
func (*OfferData) Descriptor() ([]byte, []int) {
	return file_proto_websocket_proto_rawDescGZIP(), []int{2}
}

func (x *OfferData) GetSdp() string {
	if x != nil {
		return x.Sdp
	}
	return ""
}

func (x *OfferData) GetDeviceInfo() string {
	if x != nil {
		return x.DeviceInfo
	}
	return ""
}

func (x *OfferData) GetMedia() string {
	if x != nil {
		return x.Media
	}
	return ""
}

type CandidateData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Candidate     string `protobuf:"bytes,1,opt,name=candidate,proto3" json:"candidate,omitempty"`
	SdpMid        string `protobuf:"bytes,2,opt,name=sdpMid,proto3" json:"sdpMid,omitempty"`
	SdpMLineIndex int32  `protobuf:"varint,3,opt,name=sdpMLineIndex,proto3" json:"sdpMLineIndex,omitempty"`
}

func (x *CandidateData) Reset() {
	*x = CandidateData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_websocket_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CandidateData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CandidateData) ProtoMessage() {}

func (x *CandidateData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_websocket_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CandidateData.ProtoReflect.Descriptor instead.
func (*CandidateData) Descriptor() ([]byte, []int) {
	return file_proto_websocket_proto_rawDescGZIP(), []int{3}
}

func (x *CandidateData) GetCandidate() string {
	if x != nil {
		return x.Candidate
	}
	return ""
}

func (x *CandidateData) GetSdpMid() string {
	if x != nil {
		return x.SdpMid
	}
	return ""
}

func (x *CandidateData) GetSdpMLineIndex() int32 {
	if x != nil {
		return x.SdpMLineIndex
	}
	return 0
}

type AssistData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PublicInfo []string `protobuf:"bytes,1,rep,name=publicInfo,proto3" json:"publicInfo,omitempty"`
}

func (x *AssistData) Reset() {
	*x = AssistData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_websocket_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AssistData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssistData) ProtoMessage() {}

func (x *AssistData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_websocket_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssistData.ProtoReflect.Descriptor instead.
func (*AssistData) Descriptor() ([]byte, []int) {
	return file_proto_websocket_proto_rawDescGZIP(), []int{4}
}

func (x *AssistData) GetPublicInfo() []string {
	if x != nil {
		return x.PublicInfo
	}
	return nil
}

var File_proto_websocket_proto protoreflect.FileDescriptor

var file_proto_websocket_proto_rawDesc = []byte{
	0x0a, 0x15, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x77, 0x65, 0x62, 0x73, 0x6f, 0x63, 0x6b, 0x65,
	0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x77, 0x65, 0x62, 0x73, 0x6f, 0x63, 0x6b,
	0x65, 0x74, 0x22, 0x81, 0x01, 0x0a, 0x04, 0x42, 0x6f, 0x64, 0x79, 0x12, 0x23, 0x0a, 0x04, 0x74,
	0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0f, 0x2e, 0x77, 0x65, 0x62, 0x73,
	0x6f, 0x63, 0x6b, 0x65, 0x74, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x66, 0x72, 0x6f, 0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x74, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x74, 0x6f, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49,
	0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x3e, 0x0a, 0x0a, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72,
	0x44, 0x61, 0x74, 0x61, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x64, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x73, 0x64, 0x70, 0x12, 0x1e, 0x0a, 0x0a, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65,
	0x49, 0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x64, 0x65, 0x76, 0x69,
	0x63, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x53, 0x0a, 0x09, 0x4f, 0x66, 0x66, 0x65, 0x72, 0x44,
	0x61, 0x74, 0x61, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x64, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x73, 0x64, 0x70, 0x12, 0x1e, 0x0a, 0x0a, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49,
	0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x64, 0x65, 0x76, 0x69, 0x63,
	0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x22, 0x6b, 0x0a, 0x0d, 0x43,
	0x61, 0x6e, 0x64, 0x69, 0x64, 0x61, 0x74, 0x65, 0x44, 0x61, 0x74, 0x61, 0x12, 0x1c, 0x0a, 0x09,
	0x63, 0x61, 0x6e, 0x64, 0x69, 0x64, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x63, 0x61, 0x6e, 0x64, 0x69, 0x64, 0x61, 0x74, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x64,
	0x70, 0x4d, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x64, 0x70, 0x4d,
	0x69, 0x64, 0x12, 0x24, 0x0a, 0x0d, 0x73, 0x64, 0x70, 0x4d, 0x4c, 0x69, 0x6e, 0x65, 0x49, 0x6e,
	0x64, 0x65, 0x78, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0d, 0x73, 0x64, 0x70, 0x4d, 0x4c,
	0x69, 0x6e, 0x65, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x22, 0x2c, 0x0a, 0x0a, 0x41, 0x73, 0x73, 0x69,
	0x73, 0x74, 0x44, 0x61, 0x74, 0x61, 0x12, 0x1e, 0x0a, 0x0a, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63,
	0x49, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0a, 0x70, 0x75, 0x62, 0x6c,
	0x69, 0x63, 0x49, 0x6e, 0x66, 0x6f, 0x2a, 0x50, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x09,
	0x0a, 0x05, 0x6f, 0x66, 0x66, 0x65, 0x72, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x61, 0x6e, 0x73,
	0x77, 0x65, 0x72, 0x10, 0x01, 0x12, 0x0d, 0x0a, 0x09, 0x63, 0x61, 0x6e, 0x64, 0x69, 0x64, 0x61,
	0x74, 0x65, 0x10, 0x02, 0x12, 0x0d, 0x0a, 0x09, 0x6b, 0x65, 0x65, 0x70, 0x61, 0x6c, 0x69, 0x76,
	0x65, 0x10, 0x03, 0x12, 0x0a, 0x0a, 0x06, 0x61, 0x73, 0x73, 0x69, 0x73, 0x74, 0x10, 0x04, 0x12,
	0x07, 0x0a, 0x03, 0x62, 0x79, 0x65, 0x10, 0x05, 0x42, 0x0e, 0x5a, 0x0c, 0x2e, 0x2f, 0x3b, 0x77,
	0x65, 0x62, 0x73, 0x6f, 0x63, 0x6b, 0x65, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_websocket_proto_rawDescOnce sync.Once
	file_proto_websocket_proto_rawDescData = file_proto_websocket_proto_rawDesc
)

func file_proto_websocket_proto_rawDescGZIP() []byte {
	file_proto_websocket_proto_rawDescOnce.Do(func() {
		file_proto_websocket_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_websocket_proto_rawDescData)
	})
	return file_proto_websocket_proto_rawDescData
}

var file_proto_websocket_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_websocket_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_websocket_proto_goTypes = []interface{}{
	(Type)(0),             // 0: websocket.Type
	(*Body)(nil),          // 1: websocket.Body
	(*AnswerData)(nil),    // 2: websocket.AnswerData
	(*OfferData)(nil),     // 3: websocket.OfferData
	(*CandidateData)(nil), // 4: websocket.CandidateData
	(*AssistData)(nil),    // 5: websocket.AssistData
}
var file_proto_websocket_proto_depIdxs = []int32{
	0, // 0: websocket.Body.type:type_name -> websocket.Type
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_websocket_proto_init() }
func file_proto_websocket_proto_init() {
	if File_proto_websocket_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_websocket_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Body); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_websocket_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AnswerData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_websocket_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OfferData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_websocket_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CandidateData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_websocket_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AssistData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_websocket_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_websocket_proto_goTypes,
		DependencyIndexes: file_proto_websocket_proto_depIdxs,
		EnumInfos:         file_proto_websocket_proto_enumTypes,
		MessageInfos:      file_proto_websocket_proto_msgTypes,
	}.Build()
	File_proto_websocket_proto = out.File
	file_proto_websocket_proto_rawDesc = nil
	file_proto_websocket_proto_goTypes = nil
	file_proto_websocket_proto_depIdxs = nil
}
